
services:
    core_api:


        build:
           context: .


        container_name: "api-container"
        ports:
            - "5400:5400"
        volumes:
            - ./app/:/app
#        env_file:
#            - .env
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
            - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
            - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
