
version: '3'
services:

  grafana:
    image: grafana/grafana

    ports:
      - 3000:3000

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xmx1g -Xms1g'
    ports:
      - '9200:9200'
      - '9300:9300'
    # elasticsearch browser

