
version: '3'
services:
  gradio_app:
    build:
       context: .

    container_name: "agent-conversationnel"
    ports:
      - "3200:3200"
    environment:

      - SERVER_URI_ELASTICSEARCH=${SERVER_URI_ELASTICSEARCH}
      - TOKEN_OPEN_KEY=${TOKEN_OPEN_KEY}
